name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: './.github/actions/build'

      - name: rsync
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -Srzhu --delete --exclude-from=".github/rsync-exclude.lst"
          path: ./
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}

      - name: ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            php artisan down
            php artisan clear-compiled
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan up
            cache-purge tegnersforskola.se
